### ISSUE TITLE
无法正常识别角色星级

### ISSUE THREAD

**Issue by 6634-w** [luyanci/genish-impact-picker#6]
mac版无法正常识别角色星级，名称显示”5 名字”

**Comment by luyanci** [comment]
网页那边的问题，而且这个效果不太理想，下版本考虑仅发布无自定义星数版本

**Comment by 6634-w** [comment]
我是mac版本啊




yao20100228
***@***.***




------------------ 原始邮件 ------------------
发件人: YC酱luyancib ***@***.***&gt;
发送时间: 2024年3月9日 19:06
收件人: luyanci/genish-impact-picker ***@***.***&gt;
抄送: 6634-w ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [luyanci/genish-impact-picker] 无法正常识别角色星级 (Issue #6)





 
网页那边的问题，而且这个效果不太理想，下版本考虑仅发布无自定义星数版本

**Comment by 6634-w** [comment]
希望可以优化自定义星级




yao20100228
***@***.***




------------------ 原始邮件 ------------------
发件人: YC酱luyancib ***@***.***&gt;
发送时间: 2024年3月9日 19:06
收件人: luyanci/genish-impact-picker ***@***.***&gt;
抄送: 6634-w ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [luyanci/genish-impact-picker] 无法正常识别角色星级 (Issue #6)





 
网页那边的问题，而且这个效果不太理想，下版本考虑仅发布无自定义星数版本

**Comment by luyanci** [comment]
> 我是mac版本啊
> 
> 
> 
> 
> yao20100228
> ***@***.***
> 
> 
> 
> 
> ------------------ 原始邮件 ------------------
> 发件人: YC酱luyancib ***@***.***&gt;
> 发送时间: 2024年3月9日 19:06
> 收件人: luyanci/genish-impact-picker ***@***.***&gt;
> 抄送: 6634-w ***@***.***&gt;, Author ***@***.***&gt;
> 主题: Re: [luyanci/genish-impact-picker] 无法正常识别角色星级 (Issue #6)
> 
> 
> 
> 
> 
>  
> 网页那边的问题，而且这个效果不太理想，下版本考虑仅发布无自定义星数版本
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

原版项目是靠electron+express.js把整个网页打包成了一个本地程序
